In [1]:
%matplotlib inline

#%install_ext https://raw.github.com/cpcloud/ipython-autotime/master/autotime.py
%load_ext autotime

In [2]:
import pyprind

from IPython.display import HTML


import numpy as np
from numpy import genfromtxt

import pandas as pd
from pandas import DataFrame
from pandas import Panel

import warnings


import theano

import keras
from keras.models import *
from keras.layers import *
from keras.layers.recurrent import *
from keras.utils.np_utils import to_categorical
from keras.optimizers import SGD

time: 1.82 s


Using Theano backend.


In [3]:
warnings.filterwarnings('ignore')

time: 1 ms


In [4]:
Michael = pd.read_csv('Trials/Michael.csv', header=None)

Michael.columns = ['Delta', 'Theta', 'Low_Alpha', 'High_Alpha', 'Low_Beta', 'High_Beta',
                         'Low_Gamma', 'High_Gamma', 'Attention', 'Meditation', 'Label']

Brooke = pd.read_csv('Trials/Brooke.csv', header=None)

Brooke.columns = ['Delta', 'Theta', 'Low_Alpha', 'High_Alpha', 'Low_Beta', 'High_Beta',
                  'Low_Gamma', 'High_Gamma', 'Attention', 'Meditation']

Mark = pd.read_csv('Trials/Mark.csv', header=None)

Mark.columns = ['Delta', 'Theta', 'Low_Alpha', 'High_Alpha', 'Low_Beta', 'High_Beta',
                         'Low_Gamma', 'High_Gamma', 'Attention', 'Meditation', 'Label']

Mark.shape

(2072, 11)

time: 44.5 ms


In [5]:
Mark.head()

Delta   Theta  Low_Alpha  High_Alpha  Low_Beta  High_Beta  Low_Gamma  \
0   160084   26918      11728        7755      3846       2365       1191   
1   840783   93268      11747       65774     99985      21266      40141   
2  1217192  143461      10210       11761     23137      12823       9761   
3  1030498  172887      24678        9847      9626      12134       5483   
4   612621   51515       1114       10179      9506       4846       3245   

   High_Gamma  Attention  Meditation  Label  
0        1494          1          84    NaN  
1       17742          1          84      2  
2        7286          1          84      2  
3        2068          7          88      2  
4        3569          7          75      2

time: 33 ms


In [6]:
Test_x = pd.read_csv('Trials/results.csv', header=None)

Test_x.columns = ['Delta', 'Theta', 'Low_Alpha', 'High_Alpha', 'Low_Beta', 'High_Beta',
                         'Low_Gamma', 'High_Gamma', 'Attention', 'Meditation']

Test_x['Label'] = 1

time: 7 ms


In [7]:
temp = Test_x.values

test_X_1 = temp[:, 0:9]

test_Y_1 = temp[:, 10]

#test_Y_1

time: 8.01 ms


In [8]:
Test_x_2 = pd.read_csv('Trials/results2.csv', header=None)

Test_x_2.columns = ['Delta', 'Theta', 'Low_Alpha', 'High_Alpha', 'Low_Beta', 'High_Beta',
                         'Low_Gamma', 'High_Gamma', 'Attention', 'Meditation']

Test_x_2['Label'] = 2

temp = Test_x_2.values

test_X_2 = temp[:, 0:9]

test_Y_2 = temp[:, 10]

test_Y_2

array([ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.])

time: 32.6 ms


In [9]:
Test_x_3 = pd.read_csv('Trials/results3.csv', header=None)

Test_x_3.columns = ['Delta', 'Theta', 'Low_Alpha', 'High_Alpha', 'Low_Beta', 'High_Beta',
                    'Low_Gamma', 'High_Gamma', 'Attention', 'Meditation']

Test_x_3['Label'] = 3

temp = Test_x_3.values

test_X_3 = temp[:, 0:9]

test_Y_3 = temp[:, 10]

test_Y_3

array([ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,
        3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,
        3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,
        3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,
        3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,
        3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,
        3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,
        3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,
        3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,
        3.,  3.,  3.,  3.])

time: 21 ms


In [10]:
temp_Y = pd.Series(test_Y_1)

temp_Y = pd.get_dummies(temp_Y)

test_Y = temp_Y.values

temp2 = np.zeros((len(test_Y), 2))

test_Y_1 = np.concatenate((test_Y, temp2), axis=1)

time: 7 ms


In [11]:
Brooke['Label'] = 3

Brooke.shape

(1801, 11)

time: 15 ms


In [12]:
Michael = Michael[Michael['Label'] == 1]

Michael_prime = Michael[Michael['Attention'] > 0]

Michael = Michael_prime[Michael_prime['Meditation'] > 0]


Mark_prime = Mark[Mark['Attention'] > 0]

Mark = Mark_prime[Mark_prime['Meditation'] > 0]

Mark.shape

(2072, 11)

time: 24 ms


In [13]:
Mark.head()

Delta   Theta  Low_Alpha  High_Alpha  Low_Beta  High_Beta  Low_Gamma  \
0   160084   26918      11728        7755      3846       2365       1191   
1   840783   93268      11747       65774     99985      21266      40141   
2  1217192  143461      10210       11761     23137      12823       9761   
3  1030498  172887      24678        9847      9626      12134       5483   
4   612621   51515       1114       10179      9506       4846       3245   

   High_Gamma  Attention  Meditation  Label  
0        1494          1          84    NaN  
1       17742          1          84      2  
2        7286          1          84      2  
3        2068          7          88      2  
4        3569          7          75      2

time: 27.8 ms


In [14]:
frames = [Michael.dropna()[0:1800], Mark.dropna()[0:1800], Brooke.dropna()[0:1800]]

data = pd.concat(frames, copy=False, ignore_index=True)

data = data.drop_duplicates()

data = data.dropna()

#data = data.values

time: 36 ms


In [15]:
data.shape

(5400, 11)

time: 3 ms


In [16]:
data = data.dropna()

data.shape

(5400, 11)

time: 16 ms


In [17]:
data = data.values

time: 6 ms


In [18]:
X = data[:, 0:9]

Y = data[:, 10]

X.shape

(5400, 9)

time: 8.01 ms


In [19]:
lstm_data = np.reshape(data, (data.shape[0], 1, data.shape[1]))

lstm_data.shape

(5400, 1, 11)

time: 11 ms


In [20]:
lstm_X = lstm_data[:, :, 0:9]

lstm_test_X_1 = np.reshape(test_X_1, (121, 1, 9))

lstm_test_X_2 = np.reshape(test_X_2, (121, 1, 9))

lstm_test_X_3 = np.reshape(test_X_3, (121, 1, 9))

time: 12 ms


In [21]:
Y = pd.Series(Y)

Y = pd.get_dummies(Y)

Y = Y.values

time: 10 ms


In [22]:
test_X_1.shape

(121, 9)

time: 5.51 ms


In [23]:
mlp_model = Sequential()

mlp_model.add(Dense(81, input_dim=9, init='uniform'))
mlp_model.add(Activation('softmax'))
mlp_model.add(Dropout(0.5))

mlp_model.add(Dense(256, input_dim=9, init='uniform'))
mlp_model.add(Activation('softmax'))
mlp_model.add(Dropout(0.5))

mlp_model.add(Dense(512, input_dim=9, init='uniform'))
mlp_model.add(Activation('softmax'))
mlp_model.add(Dropout(0.5))

mlp_model.add(Dense(512, input_dim=9, init='uniform'))
mlp_model.add(Activation('softmax'))
mlp_model.add(Dropout(0.5))

mlp_model.add(Dense(256, input_dim=9, init='uniform'))
mlp_model.add(Activation('softmax'))
mlp_model.add(Dropout(0.5))


mlp_model.add(Dense(3, init='uniform'))
mlp_model.add(Activation('softmax'))

sgd = SGD(lr=0.05, decay=1e-6, momentum=0.9, nesterov=True)

mlp_model.compile(loss='categorical_crossentropy',
              optimizer=sgd,
              metrics=['accuracy'])

# mlp_model.summary()

time: 1.66 s


In [24]:
# results = []


# for i in np.arange(0, 5):
#     mlp_model.fit(X, Y, batch_size=100, nb_epoch=100, verbose=1)
    
#     predicted = mlp_model.predict(test_X_1, batch_size=20)
    
#     temp = np.mean(predicted, axis=0)
    
#     results.append(temp)

# results = np.asarray(results)

# results

time: 3 ms


In [25]:
mlp_model.fit(X, Y, batch_size=100, nb_epoch=100, verbose=1)

predicted = mlp_model.predict(test_X_1, batch_size=20)

temp = np.mean(predicted, axis=0)

temp

Epoch 1/100
5400/5400 [==============================] - 2s - loss: 1.1000 - acc: 0.3350     
Epoch 2/100
5400/5400 [==============================] - 2s - loss: 1.0996 - acc: 0.3333     
Epoch 3/100
5400/5400 [==============================] - 2s - loss: 1.0995 - acc: 0.3254     
Epoch 4/100
5400/5400 [==============================] - 2s - loss: 1.0992 - acc: 0.3344     
Epoch 5/100
5400/5400 [==============================] - 2s - loss: 1.0996 - acc: 0.3283     
Epoch 6/100
5400/5400 [==============================] - 2s - loss: 1.0995 - acc: 0.3233     
Epoch 7/100
5400/5400 [==============================] - 2s - loss: 1.0990 - acc: 0.3330     
Epoch 8/100
5400/5400 [==============================] - 2s - loss: 1.0998 - acc: 0.3306     
Epoch 9/100
5400/5400 [==============================] - 2s - loss: 1.0995 - acc: 0.3283     
Epoch 10/100
5400/5400 [==============================] - 2s - loss: 1.0993 - acc: 0.3267     
Epoch 11/100
5400/5400 [==============================] - 2

array([ 0.33544576,  0.3291764 ,  0.33537713], dtype=float32)

time: 4min 17s


In [26]:
# results = []


# for i in np.arange(0, 5):
#     mlp_model.fit(X, Y, batch_size=100, nb_epoch=100, verbose=1)
    
#     predicted = mlp_model.predict(test_X_2, batch_size=20)
    
#     temp = np.mean(predicted, axis=0)
    
#     results.append(temp)

# results = np.asarray(results)

# results

time: 2 ms


In [27]:
mlp_model.fit(X, Y, batch_size=100, nb_epoch=100, verbose=1)
    
predicted = mlp_model.predict(test_X_2, batch_size=20)

temp = np.mean(predicted, axis=0)

temp

Epoch 1/100
5400/5400 [==============================] - 2s - loss: 1.0993 - acc: 0.3361     
Epoch 2/100
5400/5400 [==============================] - 2s - loss: 1.0995 - acc: 0.3228     
Epoch 3/100
5400/5400 [==============================] - 2s - loss: 1.0993 - acc: 0.3398     
Epoch 4/100
5400/5400 [==============================] - 2s - loss: 1.0993 - acc: 0.3311     
Epoch 5/100
5400/5400 [==============================] - 2s - loss: 1.0992 - acc: 0.3367     
Epoch 6/100
5400/5400 [==============================] - 2s - loss: 1.0992 - acc: 0.3346     
Epoch 7/100
5400/5400 [==============================] - 2s - loss: 1.0990 - acc: 0.3304     
Epoch 8/100
5400/5400 [==============================] - 2s - loss: 1.0989 - acc: 0.3422     
Epoch 9/100
5400/5400 [==============================] - 2s - loss: 1.0993 - acc: 0.3220     
Epoch 10/100
5400/5400 [==============================] - 2s - loss: 1.0999 - acc: 0.3252     
Epoch 11/100
5400/5400 [==============================] - 2

array([ 0.34545901,  0.33268592,  0.32185489], dtype=float32)

time: 4min 32s


In [28]:
# results = []


# for i in np.arange(0, 5):
#     mlp_model.fit(X, Y, batch_size=100, nb_epoch=100, verbose=1)
    
#     predicted = mlp_model.predict(test_X_3, batch_size=20)
    
#     temp = np.mean(predicted, axis=0)
    
#     results.append(temp)

# results = np.asarray(results)

# results

time: 3 ms


In [29]:
mlp_model.fit(X, Y, batch_size=100, nb_epoch=100, verbose=1)

predicted = mlp_model.predict(test_X_3, batch_size=20)

temp = np.mean(predicted, axis=0)

temp

Epoch 1/100
5400/5400 [==============================] - 2s - loss: 1.1010 - acc: 0.3228     
Epoch 2/100
5400/5400 [==============================] - 2s - loss: 1.0994 - acc: 0.3413     
Epoch 3/100
5400/5400 [==============================] - 2s - loss: 1.0995 - acc: 0.3178     
Epoch 4/100
5400/5400 [==============================] - 2s - loss: 1.0999 - acc: 0.3341     
Epoch 5/100
5400/5400 [==============================] - 2s - loss: 1.0992 - acc: 0.3304     
Epoch 6/100
5400/5400 [==============================] - 2s - loss: 1.0990 - acc: 0.3406     
Epoch 7/100
5400/5400 [==============================] - 2s - loss: 1.1000 - acc: 0.3302     
Epoch 8/100
5400/5400 [==============================] - 2s - loss: 1.0999 - acc: 0.3296     
Epoch 9/100
5400/5400 [==============================] - 2s - loss: 1.0999 - acc: 0.3296     
Epoch 10/100
5400/5400 [==============================] - 2s - loss: 1.0998 - acc: 0.3317     
Epoch 11/100
5400/5400 [==============================] - 2

array([ 0.34718743,  0.33805811,  0.31475446], dtype=float32)

time: 4min 30s


In [30]:
mlp_model = Sequential()

mlp_model.add(Dense(81, input_dim=9, init='uniform'))
mlp_model.add(Activation('relu'))
mlp_model.add(Dropout(0.5))


mlp_model.add(Dense(256, init='uniform'))
mlp_model.add(Activation('relu'))
mlp_model.add(Dropout(0.5))


mlp_model.add(Dense(512, init='uniform'))
mlp_model.add(Activation('relu'))
mlp_model.add(Dropout(0.5))

mlp_model.add(Dense(512, init='uniform'))
mlp_model.add(Activation('relu'))
mlp_model.add(Dropout(0.5))

mlp_model.add(Dense(256, init='uniform'))
mlp_model.add(Activation('relu'))
mlp_model.add(Dropout(0.5))


mlp_model.add(Dense(3, init='uniform'))
mlp_model.add(Activation('softmax'))

sgd = SGD(lr=0.05, decay=1e-6, momentum=0.9, nesterov=True)

mlp_model.compile(loss='categorical_crossentropy',
              optimizer=sgd,
              metrics=['accuracy'])

mlp_model.summary()

____________________________________________________________________________________________________
Layer (type)                     Output Shape          Param #     Connected to                     
dense_7 (Dense)                  (None, 81)            810         dense_input_2[0][0]              
____________________________________________________________________________________________________
activation_7 (Activation)        (None, 81)            0           dense_7[0][0]                    
____________________________________________________________________________________________________
dropout_6 (Dropout)              (None, 81)            0           activation_7[0][0]               
____________________________________________________________________________________________________
dense_8 (Dense)                  (None, 256)           20992       dropout_6[0][0]                  
___________________________________________________________________________________________

In [31]:
results = []


for i in np.arange(0, 3):
    
    mlp_model.fit(X, Y, batch_size=100, nb_epoch=100, verbose=1)
    
    predicted = mlp_model.predict(test_X_1, batch_size=20)
    
    temp = np.mean(predicted, axis=0)
    
    results.append(temp)

results = np.asarray(results)

np.mean(results, axis=0)

Epoch 1/100
5400/5400 [==============================] - 1s - loss: 10.7247 - acc: 0.3335     
Epoch 2/100
5400/5400 [==============================] - 2s - loss: 10.7454 - acc: 0.3333     
Epoch 3/100
5400/5400 [==============================] - 1s - loss: 10.7454 - acc: 0.3333     
Epoch 4/100
5400/5400 [==============================] - 2s - loss: 10.7454 - acc: 0.3333     
Epoch 5/100
5400/5400 [==============================] - 1s - loss: 10.7454 - acc: 0.3333     
Epoch 6/100
5400/5400 [==============================] - 1s - loss: 10.7454 - acc: 0.3333     
Epoch 7/100
5400/5400 [==============================] - 1s - loss: 10.7454 - acc: 0.3333     
Epoch 8/100
5400/5400 [==============================] - 1s - loss: 10.7454 - acc: 0.3333     
Epoch 9/100
5400/5400 [==============================] - 1s - loss: 10.7454 - acc: 0.3333     
Epoch 10/100
5400/5400 [==============================] - 1s - loss: 10.7454 - acc: 0.3333     
Epoch 11/100
5400/5400 [=========================

array([ 1.,  0.,  0.], dtype=float32)

time: 18min


In [32]:
results

array([[ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.]], dtype=float32)

time: 4 ms


In [33]:
results = []


for i in np.arange(0, 3):
    
    mlp_model.fit(X, Y, batch_size=100, nb_epoch=100, verbose=1)
    
    predicted = mlp_model.predict(test_X_2, batch_size=20)
    
    temp = np.mean(predicted, axis=0)
    
    results.append(temp)

results = np.asarray(results)

np.mean(results, axis=0)

Epoch 1/100
5400/5400 [==============================] - 3s - loss: 10.7454 - acc: 0.3333     
Epoch 2/100
5400/5400 [==============================] - 3s - loss: 10.7454 - acc: 0.3333     
Epoch 3/100
5400/5400 [==============================] - 3s - loss: 10.7454 - acc: 0.3333     
Epoch 4/100
5400/5400 [==============================] - 3s - loss: 10.7454 - acc: 0.3333     
Epoch 5/100
5400/5400 [==============================] - 3s - loss: 10.7454 - acc: 0.3333     
Epoch 6/100
5400/5400 [==============================] - 3s - loss: 10.7454 - acc: 0.3333     
Epoch 7/100
5400/5400 [==============================] - 3s - loss: 10.7454 - acc: 0.3333     
Epoch 8/100
5400/5400 [==============================] - 3s - loss: 10.7454 - acc: 0.3333     
Epoch 9/100
5400/5400 [==============================] - 3s - loss: 10.7454 - acc: 0.3333     
Epoch 10/100
5400/5400 [==============================] - 3s - loss: 10.7454 - acc: 0.3333     
Epoch 11/100
5400/5400 [=========================

array([ 1.,  0.,  0.], dtype=float32)

time: 18min 24s


In [34]:
lstm_model = Sequential()
lstm_model.add(LSTM(81, input_dim=9, return_sequences=True))  # returns a sequence of vectors of dimension 32
#lstm_model.add(Dropout(0.5))

lstm_model.add(LSTM(256, return_sequences=True))
#lstm_model.add(Dropout(0.5))

lstm_model.add(LSTM(512, return_sequences=True))
#lstm_model.add(Dropout(0.5))

lstm_model.add(LSTM(512, return_sequences=True))
#lstm_model.add(Dropout(0.5))

lstm_model.add(LSTM(256))
#lstm_model.add(Dropout(0.5))

lstm_model.add(Dense(3, init='uniform', activation='softmax'))

lstm_model.compile(loss='categorical_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])

lstm_model.summary()

____________________________________________________________________________________________________
Layer (type)                     Output Shape          Param #     Connected to                     
lstm_1 (LSTM)                    (None, None, 81)      29484       lstm_input_1[0][0]               
____________________________________________________________________________________________________
lstm_2 (LSTM)                    (None, None, 256)     346112      lstm_1[0][0]                     
____________________________________________________________________________________________________
lstm_3 (LSTM)                    (None, None, 512)     1574912     lstm_2[0][0]                     
____________________________________________________________________________________________________
lstm_4 (LSTM)                    (None, None, 512)     2099200     lstm_3[0][0]                     
___________________________________________________________________________________________

In [35]:
lstm_model.fit(lstm_X, Y, batch_size=100, nb_epoch=500, verbose=1)

#predicted

Epoch 1/500
5400/5400 [==============================] - 17s - loss: 0.9585 - acc: 0.4944    
Epoch 2/500
5400/5400 [==============================] - 17s - loss: 0.9269 - acc: 0.5191    
Epoch 3/500
5400/5400 [==============================] - 17s - loss: 0.9205 - acc: 0.5157    
Epoch 4/500
5400/5400 [==============================] - 17s - loss: 0.9152 - acc: 0.5215    
Epoch 5/500
5400/5400 [==============================] - 17s - loss: 0.9129 - acc: 0.5280    
Epoch 6/500
5400/5400 [==============================] - 17s - loss: 0.9055 - acc: 0.5367    
Epoch 7/500
5400/5400 [==============================] - 17s - loss: 0.9023 - acc: 0.5415    
Epoch 8/500
5400/5400 [==============================] - 17s - loss: 0.8991 - acc: 0.5483    
Epoch 9/500
5400/5400 [==============================] - 16s - loss: 0.8937 - acc: 0.5589    
Epoch 10/500
5400/5400 [==============================] - 17s - loss: 0.8908 - acc: 0.5513    
Epoch 11/500
5400/5400 [==============================] - 1

time: 2h 35min 9s


In [36]:
predicted = lstm_model.predict(lstm_test_X_1, batch_size=20)

#x = predicted[:, 1] - predicted[:, 2]

np.mean(predicted, axis=0)

array([ 0.54390568,  0.2141286 ,  0.24196565], dtype=float32)

time: 13.1 s


In [37]:
predicted = lstm_model.predict(lstm_test_X_2, batch_size=20)

#x = predicted[:, 1] - predicted[:, 2]

np.mean(predicted, axis=0)

array([ 0.1579034 ,  0.47994855,  0.36214826], dtype=float32)

time: 142 ms


In [38]:
predicted = lstm_model.predict(lstm_test_X_3, batch_size=20)

#x = predicted[:, 1] - predicted[:, 2]

np.mean(predicted, axis=0)

array([ 0.33395302,  0.38203329,  0.28401372], dtype=float32)

time: 152 ms


In [39]:
cnn_data = np.reshape(data, (data.shape[0], data.shape[1], 1))

cnn_X = cnn_data[:, 0:9, :]
cnn_Y = cnn_data[:, 10, :]

time: 4.46 ms


In [40]:
cnn_X = np.reshape(X, X.shape + (1,))

cnn_X.shape

(5400, 9, 1)

time: 17 ms


In [41]:
cnn_X.shape

(5400, 9, 1)

time: 13 ms


In [1]:
# In development

# cnn_model = Sequential()
# #cnn_model.add(Convolution1D(81, 3, input_dim=9, input_length=1800, border_mode='same'))
# cnn_model.add(Convolution1D(81, 3, activation='relu', input_dim=9))
# #cnn_model.add(Convolution1D(81, 9, activation='relu', input_shape=(9, 1)))  
# #cnn_model.add(MaxPooling1D(pool_length=2))

# cnn_model.add(Convolution1D(256, 9, activation='relu'))
# cnn_model.add(MaxPooling1D(pool_length=2))

# cnn_model.add(Convolution1D(512, 9, activation='relu'))
# cnn_model.add(MaxPooling1D(pool_length=2))


# cnn_model.add(Convolution1D(512, 9, activation='relu'))
# cnn_model.add(MaxPooling1D(pool_length=2))


# cnn_model.add(Convolution1D(256, 9, activation='relu'))
# cnn_model.add(MaxPooling1D(pool_length=2))

# #cnn_model.add(Flatten())

# cnn_model.add(Dense(3, init='uniform', activation='softmax'))

# cnn_model.compile(loss='categorical_crossentropy',
#               optimizer='rmsprop',
#               metrics=['accuracy'])


# cnn_model.summary()

In [2]:
# cnn_model.fit(lstm_X, Y, batch_size=1800, nb_epoch=500, verbose=1)

# predicted = cnn_model.predict(test_X_1, batch_size=20)